// Copyright 2023-2024 Juraj Fiala (@jurf)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

// Gamma-corrected Solarized colors
// Generated by gamma.py
#define RGB_SOLARIZED_BASE03 0, 6, 9
#define RGB_SOLARIZED_BASE02 1, 9, 14
#define RGB_SOLARIZED_BASE01 25, 40, 45
#define RGB_SOLARIZED_BASE00 33, 51, 58
#define RGB_SOLARIZED_BASE0 58, 76, 78
#define RGB_SOLARIZED_BASE1 74, 91, 91
#define RGB_SOLARIZED_BASE2 218, 206, 170
#define RGB_SOLARIZED_BASE3 250, 235, 196
#define RGB_SOLARIZED_YELLOW 118, 64, 0
#define RGB_SOLARIZED_ORANGE 152, 18, 2
#define RGB_SOLARIZED_RED 183, 8, 7
#define RGB_SOLARIZED_MAGENTA 166, 9, 57
#define RGB_SOLARIZED_VIOLET 38, 42, 141
#define RGB_SOLARIZED_BLUE 5, 66, 164
#define RGB_SOLARIZED_CYAN 6, 91, 80
#define RGB_SOLARIZED_GREEN 60, 81, 0

// The RGB struct has inconsistent ordering, so we cannot initialize with the standard macros
#define _INIT_RGB(red, green, blue) \
    { .r = red, .g = green, .b = blue }
// Workaround for macro argument expansion
// https://stackoverflow.com/a/47615680/6199517
#define INIT_RGB(...) _INIT_RGB(__VA_ARGS__)

void override_led_flags(void);